 
language: python
python:
 - "3.6"

branches:
  only:
    - master

install:
 - pip install html5validator

script: html5validator --root _build/


deploy:
  provider: surge
  project: .
  domain: victormrm.surge.sh
  skip_cleanup: true
