name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm ci
        npm run build --if-present
        npm test
        apt install nodejs build-essential libssl-dev
        npm install express
        npm install --global surge
        npm install html5-validator --save
        html5validator --root .
        surge ./index.html --token ${{ secrets.SURGE_TOKEN }}
        
        
      env:
        CI: true
