name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Test Files
      uses: Cyb3r-Jak3/html5validator-action@v0.3
      with:
        root: tests/valid/index.html
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install -g surge
        surge ./ ${{ secrets.SURGE_DOMAIN }} ${{ secrets.SURGE_TOKEN }}
        
        
      env:
        CI: true
